# Run tests and deploy to https://walles.github.io/waitinator.

name: test-and-deploy
on: [push]
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1' # Must match the android-build flutter-version below
          channel: 'stable'
      - run: flutter test

      # Deploy new main commits to Github pages
      - uses: bluefireteam/flutter-gh-pages@v7
        if: github.ref == 'refs/heads/main'
        with:
          baseHref: /waitinator/

  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.4.0
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1' # Must match the test-and-deploy flutter-version above
      - run: flutter build appbundle
